exports.seed = function(knex, Promise) {
  return knex("users_appointments")
    .del()
    .then(function() {
      return knex("users_appointments").insert([
          { user_id: 85, appointment_id: 1 },
          { user_id: 13, appointment_id: 50 },
          { user_id: 2, appointment_id: 44 },
          { user_id: 90, appointment_id: 26 },
          { user_id: 46, appointment_id: 5 },
          { user_id: 33, appointment_id: 22 },
          { user_id: 78, appointment_id: 12 },
          { user_id: 2, appointment_id: 1 },
          { user_id: 80, appointment_id: 23 },
          { user_id: 52, appointment_id: 35 },
          { user_id: 92, appointment_id: 30 },
          { user_id: 4, appointment_id: 6 },
          { user_id: 31, appointment_id: 44 },
          { user_id: 15, appointment_id: 7 },
          { user_id: 52, appointment_id: 29 },
          { user_id: 73, appointment_id: 28 },
          { user_id: 60, appointment_id: 12 },
          { user_id: 76, appointment_id: 30 },
          { user_id: 79, appointment_id: 19 },
          { user_id: 53, appointment_id: 45 },
          { user_id: 89, appointment_id: 19 },
          { user_id: 6, appointment_id: 17 },
          { user_id: 62, appointment_id: 36 },
          { user_id: 34, appointment_id: 29 },
          { user_id: 93, appointment_id: 39 },
          { user_id: 95, appointment_id: 12 },
          { user_id: 56, appointment_id: 12 },
          { user_id: 52, appointment_id: 6 },
          { user_id: 2, appointment_id: 44 },
          { user_id: 45, appointment_id: 42 },
          { user_id: 61, appointment_id: 43 },
          { user_id: 79, appointment_id: 35 },
          { user_id: 91, appointment_id: 13 },
          { user_id: 40, appointment_id: 45 },
          { user_id: 90, appointment_id: 2 },
          { user_id: 34, appointment_id: 12 },
          { user_id: 45, appointment_id: 22 },
          { user_id: 20, appointment_id: 15 },
          { user_id: 94, appointment_id: 48 },
          { user_id: 20, appointment_id: 41 },
          { user_id: 49, appointment_id: 16 },
          { user_id: 79, appointment_id: 43 },
          { user_id: 96, appointment_id: 50 },
          { user_id: 16, appointment_id: 38 },
          { user_id: 59, appointment_id: 27 },
          { user_id: 45, appointment_id: 3 },
          { user_id: 6, appointment_id: 31 },
          { user_id: 11, appointment_id: 33 },
          { user_id: 30, appointment_id: 15 },
          { user_id: 51, appointment_id: 47 }
      ]);
    });
};
